version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    image: mysql/mysql-server:latest
    env_file: .env.development.local
    volumes:
      - ./files/mysql/:/docker-entrypoint-initdb.d/

  app:
    # For building via local code use below and comment out the image field
    # build: .
    image: ananthkamath/snote:v1
    env_file: .env.development.local
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
